import type { PortalThemeMode, StudentMoodConfiguration, StudentMoodKey } from './backend-api'

export const defaultTeacherTheme: { light: PortalThemeMode; dark: PortalThemeMode } = {
  light: { headerColor: '#ffffff', headerTextColor: '#0f172a', primaryColor: '#2563eb', accentColor: '#7c3aed', backgroundColor: '#f8fafc', cardColor: '#ffffff', textColor: '#0f172a', mutedTextColor: '#64748b', backgroundEffect: 'rectangle-mesh', pointerEffect: 'glow', backgroundImage: '', backgroundImageOpacity: 0.2 },
  dark: { headerColor: '#07111f', headerTextColor: '#f8fafc', primaryColor: '#60a5fa', accentColor: '#a78bfa', backgroundColor: '#08111f', cardColor: '#111c2d', textColor: '#f8fafc', mutedTextColor: '#94a3b8', backgroundEffect: 'rectangle-mesh', pointerEffect: 'glow', backgroundImage: '', backgroundImageOpacity: 0.2 },
}

export const defaultStudentMoods: Record<StudentMoodKey, StudentMoodConfiguration> = {
  focus: { label: 'Focus', emoji: '🎯', description: 'Refined indigo and ocean tones for focused study.', light: { headerColor: '#fcfdff', headerTextColor: '#182238', primaryColor: '#3657c8', accentColor: '#268fa6', backgroundColor: '#f1f4fa', cardColor: '#ffffff', textColor: '#182238', mutedTextColor: '#68758b', backgroundEffect: 'rectangle-mesh', pointerEffect: 'sparkles', backgroundImage: '', backgroundImageOpacity: 0.2 }, dark: { headerColor: '#0b1220', headerTextColor: '#e8eef9', primaryColor: '#7892e8', accentColor: '#4db5c7', backgroundColor: '#080f1c', cardColor: '#111a2b', textColor: '#e8eef9', mutedTextColor: '#93a0b5', backgroundEffect: 'rectangle-mesh', pointerEffect: 'sparkles', backgroundImage: '', backgroundImageOpacity: 0.2 } },
  happy: { label: 'Happy', emoji: '😊', description: 'Elegant honey and rose accents on warm neutrals.', light: { headerColor: '#fffaf4', headerTextColor: '#352b25', primaryColor: '#c47a2c', accentColor: '#c65f77', backgroundColor: '#fbf6ef', cardColor: '#fffdf9', textColor: '#352b25', mutedTextColor: '#806f63', backgroundEffect: 'soft-orbs', pointerEffect: 'confetti', backgroundImage: '', backgroundImageOpacity: 0.2 }, dark: { headerColor: '#211815', headerTextColor: '#f8ece4', primaryColor: '#dda354', accentColor: '#dc7b90', backgroundColor: '#181310', cardColor: '#2a1f1a', textColor: '#f8ece4', mutedTextColor: '#bfa08a', backgroundEffect: 'soft-orbs', pointerEffect: 'confetti', backgroundImage: '', backgroundImageOpacity: 0.2 } },
  calm: { label: 'Calm', emoji: '🌿', description: 'Balanced sage and mineral tones for relaxed learning.', light: { headerColor: '#f8fbf9', headerTextColor: '#18332c', primaryColor: '#327a68', accentColor: '#5d8790', backgroundColor: '#f1f7f4', cardColor: '#fbfdfc', textColor: '#18332c', mutedTextColor: '#667c75', backgroundEffect: 'aurora', pointerEffect: 'fireflies', backgroundImage: '', backgroundImageOpacity: 0.2 }, dark: { headerColor: '#10201b', headerTextColor: '#e4f0eb', primaryColor: '#58a18c', accentColor: '#6faeb0', backgroundColor: '#0b1714', cardColor: '#142923', textColor: '#e4f0eb', mutedTextColor: '#8fb3a7', backgroundEffect: 'aurora', pointerEffect: 'fireflies', backgroundImage: '', backgroundImageOpacity: 0.2 } },
  energy: { label: 'Energy', emoji: '⚡', description: 'Premium coral and berry tones with comfortable contrast.', light: { headerColor: '#fff9f6', headerTextColor: '#3a2925', primaryColor: '#c95f46', accentColor: '#a84668', backgroundColor: '#fbf3ef', cardColor: '#fffaf7', textColor: '#3a2925', mutedTextColor: '#846b64', backgroundEffect: 'diagonal-stripes', pointerEffect: 'comet', backgroundImage: '', backgroundImageOpacity: 0.2 }, dark: { headerColor: '#24171a', headerTextColor: '#f7e9e9', primaryColor: '#df7b61', accentColor: '#c86e91', backgroundColor: '#1b1114', cardColor: '#2e1b22', textColor: '#f7e9e9', mutedTextColor: '#bd9299', backgroundEffect: 'diagonal-stripes', pointerEffect: 'comet', backgroundImage: '', backgroundImageOpacity: 0.2 } },
  dream: { label: 'Dream', emoji: '🌙', description: 'Soft aubergine and mauve for creative work.', light: { headerColor: '#fcf9fd', headerTextColor: '#302641', primaryColor: '#7253b6', accentColor: '#ad5b91', backgroundColor: '#f7f3fa', cardColor: '#fdfafe', textColor: '#302641', mutedTextColor: '#756985', backgroundEffect: 'starfield', pointerEffect: 'stars', backgroundImage: '', backgroundImageOpacity: 0.2 }, dark: { headerColor: '#1b1725', headerTextColor: '#eee8f4', primaryColor: '#9a82d0', accentColor: '#cc8fb8', backgroundColor: '#12101a', cardColor: '#292138', textColor: '#eee8f4', mutedTextColor: '#b8a7c8', backgroundEffect: 'starfield', pointerEffect: 'stars', backgroundImage: '', backgroundImageOpacity: 0.2 } },
}
