'use client'
import { useEffect, useState } from 'react'
import { Loader2, MessageSquare, Plus, Save, Send, Trash2 } from 'lucide-react'
import { getHelpVideos, getSupportThreadMessages, listSupportThreads, saveHelpVideos, sendSupportThreadMessage, type HelpVideo, type SupportMessage, type SupportThread } from '@/lib/backend-api'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { toast } from 'react-hot-toast'

export default function AdminSupportPage() {
  const [videos, setVideos] = useState<HelpVideo[]>([]); const [threads, setThreads] = useState<SupportThread[]>([]); const [selected, setSelected] = useState(''); const [messages, setMessages] = useState<SupportMessage[]>([]); const [draft, setDraft] = useState(''); const [saving, setSaving] = useState(''); const [loading, setLoading] = useState(true)
  const load = async () => { const [v, t] = await Promise.all([getHelpVideos(), listSupportThreads()]); setVideos(v.videos); setThreads(t.threads); setLoading(false) }
  useEffect(() => { void load() }, [])
  const open = async (uid: string) => { setSelected(uid); setMessages((await getSupportThreadMessages(uid)).messages) }
  const saveVideos = async () => { setSaving('videos'); try { setVideos((await saveHelpVideos(videos)).videos); toast.success('Help videos saved') } catch (e: any) { toast.error(e.message) } finally { setSaving('') } }
  const reply = async () => { if (!selected || !draft.trim()) return; setSaving('reply'); try { await sendSupportThreadMessage(selected, draft.trim()); setDraft(''); setMessages((await getSupportThreadMessages(selected)).messages); await load() } catch (e: any) { toast.error(e.message) } finally { setSaving('') } }
  return <div className='space-y-7'><div><p className='text-sm font-semibold text-primary'>SUPPORT CENTRE</p><h1 className='text-3xl font-bold'>Help videos & private support</h1><p className='mt-2 text-muted-foreground'>Publish YouTube guides and privately assist every teacher or student.</p></div>{loading ? <Loader2 className='h-7 w-7 animate-spin' /> : <><Card><CardHeader><CardTitle>Help YouTube links</CardTitle><CardDescription>Add titles, audience, and YouTube URLs. Teachers and students see only relevant guides.</CardDescription></CardHeader><CardContent className='space-y-3'>{videos.map((video, index) => <div key={video.id} className='grid gap-2 rounded-xl border p-3 md:grid-cols-[1fr_1.2fr_160px_auto]'><Input value={video.title} onChange={(e) => setVideos((items) => items.map((item, i) => i === index ? { ...item, title: e.target.value } : item))} placeholder='Video title' /><Input value={video.youtubeUrl} onChange={(e) => setVideos((items) => items.map((item, i) => i === index ? { ...item, youtubeUrl: e.target.value } : item))} placeholder='YouTube URL' /><select className='h-9 rounded-md border bg-background px-3' value={video.audience} onChange={(e) => setVideos((items) => items.map((item, i) => i === index ? { ...item, audience: e.target.value as HelpVideo['audience'] } : item))}><option value='all'>Everyone</option><option value='teacher'>Teachers</option><option value='student'>Students</option></select><Button size='icon' variant='destructive' onClick={() => setVideos((items) => items.filter((_, i) => i !== index))}><Trash2 className='h-4 w-4' /></Button></div>)}<div className='flex flex-wrap gap-2'><Button variant='outline' onClick={() => setVideos((items) => [...items, { id: crypto.randomUUID(), title: '', youtubeUrl: '', audience: 'all' }])}><Plus className='h-4 w-4' />Add video</Button><Button onClick={() => void saveVideos()} disabled={saving === 'videos'}>{saving === 'videos' ? <Loader2 className='h-4 w-4 animate-spin' /> : <Save className='h-4 w-4' />}Save videos</Button></div></CardContent></Card>
    <Card><CardHeader><CardTitle className='flex items-center gap-2'><MessageSquare className='h-5 w-5' />Teacher & student support chats</CardTitle><CardDescription>Private conversations between administrators and each account.</CardDescription></CardHeader><CardContent><div className='grid min-h-[520px] overflow-hidden rounded-xl border lg:grid-cols-[300px_1fr]'><aside className='border-r'>{threads.map((thread) => <button key={thread.id} onClick={() => void open(thread.ownerUid || thread.id)} className={'block w-full border-b p-3 text-left hover:bg-muted ' + (selected === (thread.ownerUid || thread.id) ? 'bg-primary/10' : '')}><p className='font-semibold'>{thread.ownerName || thread.ownerEmail}</p><p className='text-xs text-primary'>{thread.ownerRole}</p><p className='truncate text-sm text-muted-foreground'>{thread.lastMessage}</p></button>)}{!threads.length && <p className='p-5 text-sm text-muted-foreground'>No support requests yet.</p>}</aside><section className='flex min-h-[520px] flex-col'><div className='flex-1 space-y-2 overflow-y-auto p-4'>{messages.map((message) => <div key={message.id} className={'flex ' + (message.senderRole === 'admin' ? 'justify-end' : 'justify-start')}><div className={'max-w-[78%] rounded-2xl px-3 py-2 text-sm ' + (message.senderRole === 'admin' ? 'bg-primary text-primary-foreground' : 'bg-muted')}><p>{message.text}</p><p className='mt-1 text-[10px] opacity-70'>{message.senderName}</p></div></div>)}{selected && !messages.length && <p className='py-10 text-center text-muted-foreground'>No messages in this chat.</p>}{!selected && <p className='py-10 text-center text-muted-foreground'>Select a teacher or student.</p>}</div><div className='flex gap-2 border-t p-3'><Input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder='Reply as administrator' disabled={!selected} /><Button size='icon' onClick={() => void reply()} disabled={!selected || saving === 'reply'}>{saving === 'reply' ? <Loader2 className='h-4 w-4 animate-spin' /> : <Send className='h-4 w-4' />}</Button></div></section></div></CardContent></Card></>}</div>
}