'use client'

import { useEffect, useMemo, useState } from 'react'
import { BadgeCheck, Building2, CheckCircle2, ExternalLink, Loader2, ShieldCheck, UsersRound } from 'lucide-react'
import { toast } from 'react-hot-toast'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { assignInstitutePartner, decideInstituteAccessRequest, grantSeparateTeacherWorkspace, listInstituteAccessRequests, listInstituteSubscriptions, listInstitutes, listTeachers, setInstituteOwner, setInstituteSubscriptionStatus, type Institute, type InstituteAccessRequest, type InstituteSubscription, type InstituteSubscriptionStatus, type SubscriptionPrice, type UserProfile } from '@/lib/backend-api'

const money = (value: number) => 'LKR ' + value.toLocaleString('en-LK')
const planNames = { monthly: 'Monthly', yearly: 'Yearly', lifetime: 'Lifetime purchase' }
const fallbackPrices: Record<'monthly' | 'yearly' | 'lifetime', SubscriptionPrice> = { monthly: { current: 12000, regular: 14590 }, yearly: { current: 88000, regular: 130000 }, lifetime: { current: 478000, regular: 695000 } }

export default function AdminSubscriptionsPage() {
  const [subscriptions, setSubscriptions] = useState<InstituteSubscription[]>([])
  const [institutes, setInstitutes] = useState<Institute[]>([])
  const [teachers, setTeachers] = useState<UserProfile[]>([])
  const [requests, setRequests] = useState<InstituteAccessRequest[]>([])
  const [prices, setPrices] = useState(fallbackPrices)
  const [instituteId, setInstituteId] = useState('')
  const [ownerEmail, setOwnerEmail] = useState('')
  const [partnerUid, setPartnerUid] = useState('')
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState('')

  const load = async () => {
    setLoading(true)
    try {
      const [subscriptionData, instituteData, teacherData, requestData] = await Promise.all([listInstituteSubscriptions(), listInstitutes(), listTeachers(), listInstituteAccessRequests()])
      setSubscriptions(subscriptionData.subscriptions)
      setPrices(subscriptionData.plans || fallbackPrices)
      setInstitutes(instituteData.institutes)
      setTeachers(teacherData.teachers.filter((teacher) => teacher.status === 'approved'))
      setRequests(requestData.requests)
      setInstituteId((current) => current || instituteData.institutes[0]?.id || '')
    } catch (error: any) { toast.error(error.message || 'Could not load subscriptions') } finally { setLoading(false) }
  }
  useEffect(() => { void load() }, [])
  const current = useMemo(() => subscriptions.find((item) => item.instituteId === instituteId), [subscriptions, instituteId])
  const pendingRequests = requests.filter((request) => request.status === 'pending')
  const saveOwner = async () => { if (!instituteId || !ownerEmail.trim()) return toast.error('Select an institute owner'); setSaving('owner'); try { await setInstituteOwner({ instituteId, email: ownerEmail.trim() }); toast.success('Institute owner assigned'); await load() } catch (error: any) { toast.error(error.message || 'Could not assign owner') } finally { setSaving('') } }
  const savePartner = async () => { if (!instituteId || !partnerUid) return toast.error('Select a partner teacher'); setSaving('partner'); try { await assignInstitutePartner({ instituteId, teacherUid: partnerUid }); toast.success('Partner teacher access granted'); await load() } catch (error: any) { toast.error(error.message || 'Could not grant partner access') } finally { setSaving('') } }
  const grantWorkspace = async (teacher: UserProfile) => { const uid = teacher.uid || teacher.id; setSaving('workspace-' + uid); try { await grantSeparateTeacherWorkspace(uid); toast.success('Independent workspace granted'); await load() } catch (error: any) { toast.error(error.message || 'Could not grant workspace') } finally { setSaving('') } }
  const decideRequest = async (request: InstituteAccessRequest, approve: boolean) => { setSaving('request-' + request.id); try { await decideInstituteAccessRequest(request.id, approve); toast.success(approve ? 'Institute account access approved' : 'Institute account request rejected'); await load() } catch (error: any) { toast.error(error.message || 'Could not update request') } finally { setSaving('') } }
  const status = async (item: InstituteSubscription, value: InstituteSubscriptionStatus) => { setSaving(item.instituteId + value); try { await setInstituteSubscriptionStatus(item.instituteId, value); toast.success(value === 'active' ? 'Platform access enabled' : 'Subscription status updated'); await load() } catch (error: any) { toast.error(error.message || 'Could not update subscription') } finally { setSaving('') } }

  return <div className='space-y-7'>
    <div><p className='text-sm font-medium text-primary'>Platform sales and access</p><h1 className='mt-1 text-3xl font-bold'>Institute Subscriptions</h1><p className='mt-2 text-muted-foreground'>Review independent teacher workspaces, institute access requests, owners, partner teachers, and platform payments.</p></div>
    <div className='grid gap-4 lg:grid-cols-3'>{(['monthly', 'yearly', 'lifetime'] as const).map((plan) => <Card key={plan}><CardContent className='pt-6'><p className='font-semibold'>{planNames[plan]}</p><p className='mt-2 text-2xl font-bold text-primary'>{money(prices[plan].current)}</p><p className='mt-1 text-sm text-muted-foreground'>Actual fee <span className='line-through'>{money(prices[plan].regular)}</span></p></CardContent></Card>)}</div>
    <Card><CardHeader><CardTitle className='flex items-center gap-2'><BadgeCheck className='h-5 w-5 text-primary' />Teacher workspace requests</CardTitle><CardDescription>Approve an independent workspace for a new teacher. Institute access requests are reviewed separately below.</CardDescription></CardHeader><CardContent>{teachers.filter((teacher) => teacher.workspaceAccessStatus === 'pending').length === 0 ? <p className='text-sm text-muted-foreground'>No independent workspace requests are waiting.</p> : <div className='space-y-3'>{teachers.filter((teacher) => teacher.workspaceAccessStatus === 'pending').map((teacher) => <div key={teacher.id} className='flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4'><div><p className='font-medium'>{teacher.displayName || teacher.email}</p><p className='text-sm text-muted-foreground'>{teacher.email}</p></div><Button disabled={saving === 'workspace-' + (teacher.uid || teacher.id)} onClick={() => void grantWorkspace(teacher)}>Grant independent workspace</Button></div>)}</div>}</CardContent></Card>
    <Card><CardHeader><CardTitle className='flex items-center gap-2'><UsersRound className='h-5 w-5 text-primary' />Institute account requests</CardTitle><CardDescription>Review new institute ownership requests or requests to join an existing institute. New institutes are created with student access unavailable until their subscription payment is activated.</CardDescription></CardHeader><CardContent>{pendingRequests.length === 0 ? <p className='text-sm text-muted-foreground'>No institute account requests are waiting.</p> : <div className='space-y-3'>{pendingRequests.map((request) => <div key={request.id} className='flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4'><div><p className='font-medium'>{request.requestType === 'new-institute' ? 'New institute: ' : 'Existing institute: '}{request.instituteName}</p><p className='text-sm text-muted-foreground'>Requested by {request.teacherName || request.teacherEmail} - {request.teacherEmail}</p>{request.requestType === 'new-institute' && <div className='mt-2 text-xs text-muted-foreground'><p className='font-medium text-primary'>Requested plan: {request.subscriptionPlan || 'monthly'} - 30-day free trial</p><p>Owner: {request.ownerName || request.teacherName || 'Not provided'} ({request.ownerEmail || request.teacherEmail})</p>{request.phone && <p>Phone: {request.phone}</p>}{request.address && <p>Address: {request.address}</p>}{request.mapUrl && <p>Map: {request.mapUrl}</p>}{request.details && <p>Details: {request.details}</p>}</div>}</div><div className='flex gap-2'><Button disabled={saving === 'request-' + request.id} onClick={() => void decideRequest(request, true)}>{request.requestType === 'new-institute' ? 'Approve & create institute' : 'Approve & grant access'}</Button><Button variant='outline' disabled={saving === 'request-' + request.id} onClick={() => void decideRequest(request, false)}>Reject</Button></div></div>)}</div>}</CardContent></Card>
    <Card><CardHeader><CardTitle className='flex items-center gap-2'><ShieldCheck className='h-5 w-5 text-primary' />Institute owner and partner access</CardTitle><CardDescription>Assign an owner first. The owner can send 30-day email invitations; admins can also grant access directly.</CardDescription></CardHeader><CardContent className='space-y-4'><label className='block text-sm font-medium'>Institute<select className='mt-1 h-10 w-full rounded-md border bg-background px-3' value={instituteId} onChange={(event) => setInstituteId(event.target.value)}><option value=''>Select institute</option>{institutes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className='grid gap-3 md:grid-cols-2'><label className='block text-sm font-medium'>Institute owner<select className='mt-1 h-10 w-full rounded-md border bg-background px-3' value={ownerEmail} onChange={(event) => setOwnerEmail(event.target.value)}><option value=''>Select approved teacher</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.email || ''}>{teacher.displayName || teacher.email} — {teacher.email}</option>)}</select></label><div className='flex items-end'><Button disabled={saving === 'owner' || !ownerEmail} onClick={() => void saveOwner()}>Assign owner</Button></div></div><p className='text-sm text-muted-foreground'>Current owner: {current?.ownerEmail || 'Not assigned'}</p><div className='grid gap-3 md:grid-cols-[1fr_auto]'><select className='h-10 rounded-md border bg-background px-3' value={partnerUid} onChange={(event) => setPartnerUid(event.target.value)}><option value=''>Select approved teacher as partner</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.displayName || teacher.email} — {teacher.email}</option>)}</select><Button variant='outline' disabled={!partnerUid || saving === 'partner'} onClick={() => void savePartner()}>Grant partner access</Button></div></CardContent></Card>
    <Card><CardHeader><CardTitle className='flex items-center gap-2'><Building2 className='h-5 w-5 text-primary' />Submitted subscription payments</CardTitle><CardDescription>Review payment slips and enable or disable the relevant independent teacher or institute account.</CardDescription></CardHeader><CardContent>{loading ? <div className='flex items-center gap-2 py-10 text-muted-foreground'><Loader2 className='h-5 w-5 animate-spin' />Loading subscriptions…</div> : <div className='space-y-4'>{subscriptions.map((item) => <div key={item.instituteId} className='rounded-xl border p-4'><div className='flex flex-wrap items-center justify-between gap-4'><div><p className='font-semibold'>{item.instituteName || 'Unnamed workspace'}</p><p className='mt-1 text-sm text-muted-foreground'>{item.instituteId.startsWith('solo:') ? <>{item.tierId || 'Teacher plan'} · {money(item.price || 0)}</> : <>{planNames[item.plan]} · {money(prices[item.plan].current)}</>} · Owner: {item.ownerEmail || 'Not assigned'}</p><p className='mt-1 text-xs text-muted-foreground'>Status: {item.status}{item.submittedAt ? ' · Submitted ' + new Date(item.submittedAt).toLocaleString() : ''}</p>{item.note && <p className='mt-2 text-sm'>{item.note}</p>}</div><div className='flex flex-wrap gap-2'>{item.slipUrl && <a href={item.slipUrl} target='_blank' rel='noreferrer'><Button variant='outline'><ExternalLink className='h-4 w-4' />View slip</Button></a>}<Button disabled={saving === item.instituteId + 'active' || !item.slipUrl} onClick={() => void status(item, 'active')}><CheckCircle2 className='h-4 w-4' />Enable</Button><Button variant='destructive' disabled={saving === item.instituteId + 'unavailable'} onClick={() => void status(item, 'unavailable')}>Disable</Button></div></div></div>)}{subscriptions.length === 0 && <p className='py-10 text-center text-muted-foreground'>No subscriptions yet.</p>}</div>}</CardContent></Card>
  </div>
}